name: 自動化

on:
  schedule:
    - cron: "0 8,20 * * *"
jobs:
  automation:
    name: 自動化
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bahamut Automation
        uses: JacobLinCool/Bahamut-Automation@action
        with:
          modules: "report,ad_handler,cookie_login,sign,guild,answer,lottery,del_mail,report,line_notify,issue"
          parameters: '{ "lottery_max_parallel": 3, "del_mail_match": [ { "title": "【勇者福利社】成功獲得抽獎資格通知信" }, { "title": "動畫瘋獲獎通知" } ] }'
          secrets: ${{ secrets.SECRETS }}
      - uses: gautamkrishnar/keepalive-workflow@master
© 2022 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contac
